import { Transaction } from '@/types';
import { useAuth } from '@/contexts/AuthContext';
import { formatNaira, formatFullDate } from '@/lib/utils';
import { X, Share2, BookOpen, TrendingUp, TrendingDown } from 'lucide-react';

interface Props {
  transaction: Transaction;
  onClose: () => void;
}

export default function ReceiptModal({ transaction: tx, onClose }: Props) {
  const { user } = useAuth();
  const isIncome = tx.type === 'income';

  const handleWhatsAppShare = () => {
    const typeLabel = isIncome ? 'SALE RECEIPT' : 'EXPENSE RECORD';
    const msg =
      `📋 *${typeLabel}*\n` +
      `━━━━━━━━━━━━━━━━━━\n` +
      `🏪 *BetaBook*\n` +
      `📅 Date: ${formatFullDate(tx.created_at)}\n` +
      `━━━━━━━━━━━━━━━━━━\n` +
      (tx.item_name ? `📦 Item: ${tx.item_name}\n` : '') +
      (tx.category ? `📂 Category: ${tx.category}\n` : '') +
      (tx.customer_name ? `👤 Customer: ${tx.customer_name}\n` : '') +
      (tx.customer_phone ? `📞 Phone: ${tx.customer_phone}\n` : '') +
      `━━━━━━━━━━━━━━━━━━\n` +
      `💰 Amount: *${formatNaira(tx.amount)}*\n` +
      (tx.payment_status ? `✅ Status: ${tx.payment_status === 'paid' ? 'PAID' : 'CREDIT (OWING)'}\n` : '') +
      (tx.notes ? `📝 Notes: ${tx.notes}\n` : '') +
      `━━━━━━━━━━━━━━━━━━\n` +
      `_Generated by BetaBook_`;
    const num = tx.customer_phone
      ? (() => {
          const c = tx.customer_phone.replace(/\D/g, '');
          return c.startsWith('0') ? `234${c.slice(1)}` : c;
        })()
      : '';
    window.open(
      `https://wa.me/${num}?text=${encodeURIComponent(msg)}`,
      '_blank'
    );
  };

  return (
    <div className="fixed inset-0 z-50 flex items-end md:items-center justify-center bg-black/40 backdrop-blur-sm">
      <div className="w-full max-w-sm bg-white rounded-t-3xl md:rounded-2xl shadow-2xl overflow-hidden animate-[fade-up_0.25s_ease-out_forwards]">
        {/* Header */}
        <div className="flex items-center justify-between px-5 py-4 border-b border-gray-100">
          <div className="flex items-center gap-2">
            <BookOpen className="w-4 h-4 text-blue-500" />
            <h3 className="font-heading font-bold text-gray-900 text-sm">
              {isIncome ? 'Sale Receipt' : 'Expense Record'}
            </h3>
          </div>
          <button onClick={onClose}
            className="w-8 h-8 rounded-full bg-gray-100 flex items-center justify-center hover:bg-gray-200 transition-colors">
            <X className="w-4 h-4 text-gray-500" />
          </button>
        </div>

        {/* Receipt Body */}
        <div className="px-5 py-5">
          {/* Amount */}
          <div className={`rounded-2xl p-5 mb-5 text-center ${isIncome ? 'bg-emerald-50' : 'bg-red-50'}`}>
            <div className={`w-10 h-10 rounded-full flex items-center justify-center mx-auto mb-2 ${
              isIncome ? 'bg-emerald-100' : 'bg-red-100'
            }`}>
              {isIncome
                ? <TrendingUp className="w-5 h-5 text-emerald-600" />
                : <TrendingDown className="w-5 h-5 text-red-500" />}
            </div>
            <p className={`text-3xl font-heading font-bold ${isIncome ? 'text-emerald-700' : 'text-red-600'}`}>
              {formatNaira(tx.amount)}
            </p>
            {tx.payment_status && (
              <span className={`inline-block mt-1.5 px-2.5 py-0.5 rounded-full text-xs font-semibold ${
                tx.payment_status === 'paid'
                  ? 'bg-emerald-200 text-emerald-800'
                  : 'bg-amber-200 text-amber-800'
              }`}>
                {tx.payment_status === 'paid' ? 'PAID' : 'CREDIT — OWING'}
              </span>
            )}
          </div>

          {/* Details */}
          <div className="space-y-2.5">
            <ReceiptRow label="Date" value={formatFullDate(tx.created_at)} />
            {tx.item_name && <ReceiptRow label="Item / Product" value={tx.item_name} />}
            {tx.category && <ReceiptRow label="Category" value={tx.category} />}
            {tx.customer_name && <ReceiptRow label="Customer" value={tx.customer_name} />}
            {tx.customer_phone && <ReceiptRow label="Phone" value={tx.customer_phone} />}
            {tx.notes && <ReceiptRow label="Notes" value={tx.notes} />}
            <ReceiptRow label="Merchant" value={user?.full_name || user?.email || 'BetaBook User'} />
          </div>

          <div className="border-t border-dashed border-gray-200 mt-4 pt-3 text-center">
            <p className="text-gray-400 text-xs">Generated by BetaBook · Smart Market Ledger</p>
          </div>
        </div>

        {/* Share Button */}
        <div className="px-5 pb-5">
          <button onClick={handleWhatsAppShare}
            className="w-full py-3 rounded-xl font-semibold text-white text-sm bg-[#25D366] hover:bg-[#1ebe5b] flex items-center justify-center gap-2 transition-all active:scale-[0.98]">
            <Share2 className="w-4 h-4" />
            Share via WhatsApp
          </button>
        </div>
      </div>
    </div>
  );
}

function ReceiptRow({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-start justify-between gap-4">
      <span className="text-gray-400 text-xs flex-shrink-0 pt-0.5">{label}</span>
      <span className="text-gray-800 text-xs font-medium text-right">{value}</span>
    </div>
  );
}
